---
name: Egg-Plugin-SessionKit
version: 3.01
author:
  - 'Masatoshi Mizuno E<lt>lusheE<64>cpan.orgE<gt>'
abstract: lib/Egg/Plugin/SessionKit.pm
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Cache::Cache: 1.05
  Convert::UU: 0.52
  Data::UUID: 1.14
  Egg::Release: 3.00
  Egg::Release::DBI: 0.01
  Egg::Release::DBIC: 0.01
  Storable: 2.18
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Time::Piece::MySQL: 0.05
provides:
  Egg::Helper::Model::Session:
    file: lib/Egg/Helper/Model/Session.pm
    version: 0.01
  Egg::Model::Session:
    file: lib/Egg/Model/Session.pm
    version: 0.01
  Egg::Model::Session::Base::DBI:
    file: lib/Egg/Model/Session/Base/DBI.pm
    version: 0.01
  Egg::Model::Session::Base::DBIC:
    file: lib/Egg/Model/Session/Base/DBIC.pm
  Egg::Model::Session::Base::FileCache:
    file: lib/Egg/Model/Session/Base/FileCache.pm
    version: 3.00
  Egg::Model::Session::Bind::Cookie:
    file: lib/Egg/Model/Session/Bind/Cookie.pm
    version: 0.01
  Egg::Model::Session::ID::IPaddr:
    file: lib/Egg/Model/Session/ID/IPaddr.pm
    version: 0.01
  Egg::Model::Session::ID::MD5:
    file: lib/Egg/Model/Session/ID/MD5.pm
    version: 0.01
  Egg::Model::Session::ID::SHA1:
    file: lib/Egg/Model/Session/ID/SHA1.pm
    version: 0.01
  Egg::Model::Session::ID::UUID:
    file: lib/Egg/Model/Session/ID/UUID.pm
    version: 0.01
  Egg::Model::Session::ID::UniqueID:
    file: lib/Egg/Model/Session/ID/UniqueID.pm
    version: 0.01
  Egg::Model::Session::Manager::Base:
    file: lib/Egg/Model/Session/Manager/Base.pm
    version: 0.01
  Egg::Model::Session::Manager::TieHash:
    file: lib/Egg/Model/Session/Manager/TieHash.pm
    version: 0.01
  Egg::Model::Session::Plugin::AbsoluteIP:
    file: lib/Egg/Model/Session/Plugin/AbsoluteIP.pm
    version: 0.01
  Egg::Model::Session::Plugin::AgreeAgent:
    file: lib/Egg/Model/Session/Plugin/AgreeAgent.pm
    version: 0.01
  Egg::Model::Session::Plugin::CclassIP:
    file: lib/Egg/Model/Session/Plugin/CclassIP.pm
    version: 0.01
  Egg::Model::Session::Plugin::Ticket:
    file: lib/Egg/Model/Session/Plugin/Ticket.pm
    version: 0.01
  Egg::Model::Session::Store::Base64:
    file: lib/Egg/Model/Session/Store/Base64.pm
    version: 0.01
  Egg::Model::Session::Store::UUencode:
    file: lib/Egg/Model/Session/Store/UUencode.pm
    version: 0.01
  Egg::Model::Session::handler:
    file: lib/Egg/Model/Session.pm
  Egg::Plugin::Session:
    file: lib/Egg/Plugin/Session.pm
    version: 0.01
  Egg::Plugin::SessionKit:
    file: lib/Egg/Plugin/SessionKit.pm
    version: 3.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
