---
name: Egg-Plugin-SessionKit
version: 2.10
author:
  - 'Masatoshi Mizuno E<lt>lusheE<64>cpan.orgE<gt>'
abstract: lib/Egg/Plugin/SessionKit.pm
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Cache::Cache: 1.05
  Class::Data::Inheritable: 0.06
  Digest::MD5: 2.36
  Digest::SHA1: 2.11
  Egg::Plugin::IxHash: 2.03
  Egg::Release: 2.25
  MIME::Base64: 3.07
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Egg::Plugin::SessionKit:
    file: lib/Egg/Plugin/SessionKit.pm
    version: 2.10
  Egg::Plugin::SessionKit::Base::DBI:
    file: lib/Egg/Plugin/SessionKit/Base/DBI.pm
    version: 2.10
  Egg::Plugin::SessionKit::Base::DBIC:
    file: lib/Egg/Plugin/SessionKit/Base/DBIC.pm
    version: 2.01
  Egg::Plugin::SessionKit::Base::FileCache:
    file: lib/Egg/Plugin/SessionKit/Base/FileCache.pm
    version: 2.10
  Egg::Plugin::SessionKit::Bind::Cookie:
    file: lib/Egg/Plugin/SessionKit/Bind/Cookie.pm
    version: 2.10
  Egg::Plugin::SessionKit::Issue::MD5:
    file: lib/Egg/Plugin/SessionKit/Issue/MD5.pm
    version: 2.10
  Egg::Plugin::SessionKit::Issue::UUID:
    file: lib/Egg/Plugin/SessionKit/Issue/UUID.pm
    version: 2.10
  Egg::Plugin::SessionKit::Issue::UniqueID:
    file: lib/Egg/Plugin/SessionKit/Issue/UniqueID.pm
    version: 2.10
  Egg::Plugin::SessionKit::Store::Base64:
    file: lib/Egg/Plugin/SessionKit/Store/Base64.pm
    version: 2.01
  Egg::Plugin::SessionKit::Store::Plain:
    file: lib/Egg/Plugin/SessionKit/Store/Plain.pm
    version: 2.01
  Egg::Plugin::SessionKit::base:
    file: lib/Egg/Plugin/SessionKit.pm
  Egg::Plugin::SessionKit::handler:
    file: lib/Egg/Plugin/SessionKit.pm
  Egg::Plugin::SessionKit::handler::TieHash:
    file: lib/Egg/Plugin/SessionKit.pm
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
